# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Joseph Warren
# Generated on: 2/7/2019

@{
    RootModule        = 'VSCodeBackup.psm1'
    ModuleVersion     = '0.1.6'
    GUID              = 'aa70e5b3-c212-49a8-b566-4f4e20484e60'
    Author            = 'Joseph Warren'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Joseph Warren. All rights reserved.'
    Description       = 'Simple module to backup and restore VS Code extensions and settings. Useful for transferring to an offline network.'
    FunctionsToExport = @('Backup-VSCode', 'Restore-VSCode')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags       = @('vscode', 'backup', 'restore')
            LicenseUri = 'https://github.com/luzkenin/VSCodeBackup/blob/master/LICENSE.txt'
            ProjectUri = 'https://github.com/luzkenin/VSCodeBackup'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

